// <auto-generated />
using DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FUIServerSample.Layer.DataLayer.Migrations
{
    [DbContext(typeof(DemoContext))]
    partial class DemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FUIServerSample.Layer.DataLayer.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cellular")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cust_Type")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Postal_Code")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tax_Id")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            Cellular = "",
                            City = "Berlin",
                            Country = "Germany",
                            Cust_Type = "",
                            Email = "",
                            FirstName = "Maria",
                            LastName = "Anders",
                            Phone = "030-0074321",
                            Postal_Code = "",
                            SSN = "",
                            Tax_Id = ""
                        },
                        new
                        {
                            Id = 2,
                            Address = "",
                            Cellular = "",
                            City = "México D.F.",
                            Country = "México",
                            Cust_Type = "",
                            Email = "",
                            FirstName = "Ana",
                            LastName = "Trujillo",
                            Phone = "(5) 555-4729",
                            Postal_Code = "",
                            SSN = "",
                            Tax_Id = ""
                        },
                        new
                        {
                            Id = 3,
                            Address = "",
                            Cellular = "",
                            City = "México D.F.",
                            Country = "México",
                            Cust_Type = "",
                            Email = "",
                            FirstName = "Antonio",
                            LastName = "Moreno",
                            Phone = "(5) 555-3932",
                            Postal_Code = "",
                            SSN = "",
                            Tax_Id = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
